### ISSUE TITLE
Error while completing request

### ISSUE THREAD

**Issue by sccardais** [meistrari/prompts-royale#4]
I'm receiving this error.

_"Error while completing request
You exceeded your current quota, please check your plan and billing details."_

I entered Mmy API key for my OpenAI Pro account into Prompt-Royale > Settings. My API key is valid.

In the "Description" field, I entered, "Categorize questions into non-overlapping groups."

In the "Prompt Candidates" field I clicked "Generate Prompts" using either 5 or 10.

Am I doing something wrong?

Thank you.

ScottC
Saluda, NC

**Comment by henrycunh** [comment]
You're probably using a free account, which has very low limits for usage!

I suggest upgrading your plan to `pay as you go` on https://platform.openai.com

You can check for more [details here](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details)

**Comment by sccardais** [comment]
Actually, I'm not using a Free Account. I've been a Pro user for months.

ChatGPT acknowledges that I'm a Pro account user but my OpenAI Account
management page says I have a Free Account. I'm paying $20/month but these
payments aren't showing up in the Billing area of OpenAi.

So, ChatGPT recognizes me as a Pro account but OpenAI billing doesn't. It's
a mystery.

I sent a Chat Message to OpenAI this morning to get resolved.

Thanks for your reply.

ScottC
Saluda, NC

**Comment by henrycunh** [comment]
I see! What happens is that the OpenAI API platform and OpenAI's ChatGPT plans are separated.

Paying for ChatGPT Plus doesn't mean that you've also input billing information and switched your plan on the OpenAI platform to `pay-as-you-go`.

You can go to https://platform.openai.com/account/billing/overview to check this out!

**Comment by sccardais** [comment]
Thanks, Henry:

I know you're not Tech Support for OpenAI (!!) but do you know if this
means that I have to pay an additional $20/month for an OpenAI account or
that I need to convert my ChatGPT account to an OpenAI account or something
in between?

I went to the link you sent above and that question wasn't addressed. It
gave me the opportunity to input new credit card info but it didn't give me
the option to input my current credentials and convert.

As I said, I have a question into OpenAI billing dept but they openly said
it can take up to a week for them to reply.

Thanks again for your help -- especially on a Sunday!

ScottC
Saluda, NC

**Comment by sccardais** [comment]
Henry:

I got this reply from OpenAI just a minute ago. So, I guess I need a
separate OpenAI account to use Prompt-Royale.

Hello,
﻿
﻿Thank you for reaching out to OpenAI support.

We sincerely apologize for the confusion. The OpenAI API and ChatGPT Plus
subscription are billed separately. The API has its own pricing, which can
be found here <https://openai.com/pricing>. The ChatGPT Plus subscription
covers usage on the ChatGPT website <http://chat.openai.com/> only and
costs $20/month.

Please let us know if you have any questions.

Best,
﻿Faye
﻿OpenAI Support

**Comment by henrycunh** [comment]
You don't need a separate account! You're opting into the pay-as-you-go plan by inputting your billing information. 

It will charge you only for what you use :] You can track your usage to date on the top right corner of the application.
