### ISSUE TITLE
where are responses stored?

### ISSUE THREAD

**Issue by fredzannarbor** [meistrari/prompts-royale#5]
Are they in the local file system somewhere?

I would like to be able to inspect them.

**Comment by henrycunh** [comment]
They're stored in LocalStorage, through this composable I made: https://github.com/meistrari/prompts-royale/blob/main/utils/synced-state.ts

You can check its usage and respective local storage keys here:
https://github.com/meistrari/prompts-royale/blob/main/composables/auto-prompter.ts
