### ISSUE TITLE
How this works compared to gpt-prompt-engineer

### ISSUE THREAD

**Issue by fredzannarbor** [meistrari/prompts-royale#6]
I want to check something on my understanding here. Am I right that this works differently from gpe in that the prompt creation for test data is more elaborate?

GPE  ```
description = "Given a prompt, generate a landing page headline." # this style of description tends to work well

test_cases = [
    {
        'prompt': 'Promoting an innovative new fitness app, Smartly',
    },
    {
        'prompt': 'Why a vegan diet is beneficial for your health',
    },
    {
        'prompt': 'Introducing a new online course on digital marketing',
    },
```
Where as prompts-royale (great name btw)  asks for

'final objective':,

{ 'scenario':,
'expected outcome' ...}

**Comment by henrycunh** [comment]
Description → Final Objective
Test Case [Prompt] → Scenario

You can leave the expected outcome unfilled if you don't have any in mind! It will use a ranking agent to choose a winner in those cases.
